server.port=0

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.datasource.url=jdbc:h2:mem:pagos_test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.flyway.enabled=false

logging.level.com.duoc.ms_pagos=WARN
logging.level.org.springframework=WARN
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false